#!/usr/bin/env bash
# Подготовка стенда SD-WAN: генерируем ключи WireGuard, раскладываем
# конфиги и Python-агента по каталогам обоих филиалов.
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

WG_PORT=51199
OVERLAY_MSK="172.16.99.1/30"
OVERLAY_SPB="172.16.99.2/30"
OVERLAY_NETS="172.16.99.0/24"

# Транспортные адреса соседнего филиала по каждому каналу
SPB_FIBER="10.10.0.20:${WG_PORT}"
SPB_SAT="10.20.0.20:${WG_PORT}"
MSK_FIBER="10.10.0.10:${WG_PORT}"
MSK_SAT="10.20.0.10:${WG_PORT}"

mkdir -p sites/msk/agent sites/spb/agent

echo "[*] Генерация ключевых пар WireGuard..."
MSK_PRIV="$(wg genkey)"
MSK_PUB="$(printf '%s' "$MSK_PRIV" | wg pubkey)"
SPB_PRIV="$(wg genkey)"
SPB_PUB="$(printf '%s' "$SPB_PRIV" | wg pubkey)"

write_wg_config() {
    local out=$1 self_addr=$2 self_priv=$3 peer_pub=$4 peer_endpoint=$5

    cat > "$out" <<CONF
# auto-generated by bootstrap.sh - не редактировать вручную
[Interface]
Address    = ${self_addr}
ListenPort = ${WG_PORT}
PrivateKey = ${self_priv}

[Peer]
PublicKey  = ${peer_pub}
Endpoint   = ${peer_endpoint}
AllowedIPs = ${OVERLAY_NETS}
PersistentKeepalive = 15
CONF
}

write_wg_config sites/msk/wg0.conf "$OVERLAY_MSK" "$MSK_PRIV" "$SPB_PUB" "$SPB_FIBER"
write_wg_config sites/spb/wg0.conf "$OVERLAY_SPB" "$SPB_PRIV" "$MSK_PUB" "$MSK_FIBER"

echo "[*] Сборка Python-агента link_watchdog.py..."
write_watchdog() {
    local out=$1 peer_pub=$2 ep_fiber=$3 ep_sat=$4

    cat > "$out" <<PY
#!/usr/bin/env python3
"""link_watchdog - наблюдает за двумя WAN-каналами и переключает
endpoint WireGuard-пира на лучший. Реализует упрощённую логику SD-WAN:
динамический выбор пути на основании метрик RTT и потерь."""

import logging
import re
import shutil
import subprocess
import sys
import time
from collections import deque
from dataclasses import dataclass

WG_IFACE      = "wg0"
PEER_KEY      = "${peer_pub}"
EP_FIBER      = "${ep_fiber}"
EP_SAT        = "${ep_sat}"

PROBE_PERIOD   = 4         # секунд между опросами
PROBE_PACKETS  = 4
SAMPLE_DEPTH   = 4         # сколько последних замеров усреднять
LOSS_GUARD     = 25.0      # %, выше - канал считается непригодным
RTT_HYSTERESIS = 1.20      # на сколько раз должен быть лучше, чтобы переключиться

RE_RTT  = re.compile(r"min/avg/max[^=]*=\s*[\d.]+/([\d.]+)/")
RE_LOSS = re.compile(r"(\d+(?:\.\d+)?)% packet loss")

log = logging.getLogger("watchdog")


@dataclass
class Sample:
    rtt: float
    loss: float


def measure(host: str) -> Sample:
    """Простой ICMP-замер. Возвращает Sample со средним RTT и % потерь."""
    try:
        proc = subprocess.run(
            ["ping", "-q", "-c", str(PROBE_PACKETS), "-W", "1", host],
            capture_output=True, text=True, timeout=PROBE_PACKETS + 2,
        )
        blob = proc.stdout + proc.stderr
        rtt  = float(m.group(1)) if (m := RE_RTT.search(blob))  else 9999.0
        loss = float(m.group(1)) if (m := RE_LOSS.search(blob)) else 100.0
        return Sample(rtt=rtt, loss=loss)
    except Exception as exc:
        log.debug("ping %s failed: %s", host, exc)
        return Sample(rtt=9999.0, loss=100.0)


class LinkWatcher:
    """Хранит скользящее окно метрик по каналу и считает агрегаты."""

    def __init__(self, name: str, endpoint: str):
        self.name = name
        self.endpoint = endpoint
        self.host = endpoint.split(":", 1)[0]
        self.window: deque[Sample] = deque(maxlen=SAMPLE_DEPTH)

    def poll(self) -> Sample:
        s = measure(self.host)
        self.window.append(s)
        return s

    @property
    def avg_rtt(self) -> float:
        return sum(s.rtt for s in self.window) / max(1, len(self.window))

    @property
    def avg_loss(self) -> float:
        return sum(s.loss for s in self.window) / max(1, len(self.window))

    @property
    def healthy(self) -> bool:
        return bool(self.window) and self.avg_loss < LOSS_GUARD


def retarget(endpoint: str) -> None:
    """Сдвигает endpoint у пира - это и есть переключение пути."""
    log.warning("→ переключаемся на endpoint %s", endpoint)
    subprocess.run(
        ["wg", "set", WG_IFACE, "peer", PEER_KEY, "endpoint", endpoint],
        check=False,
    )


def pick_best(fiber: LinkWatcher, sat: LinkWatcher, current: str | None) -> str | None:
    # Жёсткое требование: канал должен быть здоровым.
    fiber_ok, sat_ok = fiber.healthy, sat.healthy
    if not fiber_ok and not sat_ok:
        return current
    if fiber_ok and not sat_ok:
        return "fiber"
    if sat_ok and not fiber_ok:
        return "sat"

    # Оба живы - предпочитаем оптику, переключаемся только если спутник
    # ощутимо быстрее с учётом гистерезиса (защита от флапа).
    if current == "sat" and fiber.avg_rtt * RTT_HYSTERESIS < sat.avg_rtt:
        return "fiber"
    if current == "fiber" and sat.avg_rtt * RTT_HYSTERESIS < fiber.avg_rtt:
        return "sat"
    return current or "fiber"


def main() -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
    )

    if shutil.which("wg") is None:
        log.error("wireguard-tools не установлен")
        return 1

    fiber = LinkWatcher("fiber", EP_FIBER)
    sat   = LinkWatcher("sat",   EP_SAT)

    log.info("watchdog запущен; пир %s...", PEER_KEY[:12])
    log.info("каналы: fiber=%s, sat=%s", EP_FIBER, EP_SAT)

    active: str | None = None
    endpoints = {"fiber": EP_FIBER, "sat": EP_SAT}

    while True:
        fiber.poll()
        sat.poll()

        chosen = pick_best(fiber, sat, active)

        if chosen and chosen != active:
            retarget(endpoints[chosen])
            active = chosen

        log.info(
            "fiber %5.1f ms / %4.1f%%  |  sat %5.1f ms / %4.1f%%  |  active=%s",
            fiber.avg_rtt, fiber.avg_loss,
            sat.avg_rtt,   sat.avg_loss,
            active,
        )
        time.sleep(PROBE_PERIOD)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(0)
PY
}

write_watchdog sites/msk/agent/link_watchdog.py "$SPB_PUB" \
    "10.10.0.20:${WG_PORT}" "10.20.0.20:${WG_PORT}"
write_watchdog sites/spb/agent/link_watchdog.py "$MSK_PUB" \
    "10.10.0.10:${WG_PORT}" "10.20.0.10:${WG_PORT}"

echo "[*] Создание container_init.sh..."
cat > container_init.sh <<'INIT'
#!/usr/bin/env bash
# Точка входа для контейнера филиала.
#  1) находит интерфейсы оптики и спутника по их подсетям;
#  2) накладывает netem-имитацию реальных характеристик каналов;
#  3) поднимает WireGuard и запускает Python-агента.
set -e

iface_for_subnet() {
    ip -4 -o addr show \
        | awk -v p="$1" '$4 ~ "^"p {print $2; exit}'
}

IF_FIBER="$(iface_for_subnet '10\.10\.')"
IF_SAT="$(iface_for_subnet  '10\.20\.')"

echo "[init] оптика  : ${IF_FIBER:-<none>}"
echo "[init] спутник : ${IF_SAT:-<none>}"

# Оптика - почти идеальна, лишь лёгкий джиттер
if [ -n "${IF_FIBER}" ]; then
    tc qdisc add dev "${IF_FIBER}" root netem delay 12ms 2ms
fi

# Спутник - большая задержка и заметные потери
if [ -n "${IF_SAT}" ]; then
    tc qdisc add dev "${IF_SAT}" root netem delay 220ms 25ms loss 6%
fi

wg-quick up wg0
echo "[init] overlay поднят, запускаем link_watchdog"

python3 -u /opt/sdwan/agent/link_watchdog.py &

# держим контейнер живым
exec tail -f /dev/null
INIT

chmod +x container_init.sh

echo
echo "[+] Готово. Дальше:"
echo "    docker compose up --build -d"
