#!/usr/bin/env bash
# Готовит площадку для классического WAN на IPsec: раскладывает конфиги
# strongSwan для двух филиалов. Туннель завязан только на основной канал
# (link_primary) - резервная линия физически есть, но в IKE-политике
# не упомянута, чтобы продемонстрировать жёсткую привязку к одному пути.
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

PSK_SECRET="${PSK_SECRET:-r0tate-Me-pl3ase}"

# Транспортные адреса по основному каналу
A_PRIMARY="10.50.0.11"
B_PRIMARY="10.50.0.22"

# Защищаемые "внутренние" хосты (повешены на loopback)
A_INNER="192.168.77.1/32"
B_INNER="192.168.77.2/32"

mkdir -p nodes/a nodes/b

write_swanctl() {
    local out=$1
    local self_id=$2 peer_id=$3
    local self_ip=$4 peer_ip=$5
    local self_inner=$6 peer_inner=$7

    cat > "$out" <<CONF
# auto-generated by forge_tunnel.sh - не редактировать руками
connections {
    site-to-site {
        version       = 2
        local_addrs   = ${self_ip}
        remote_addrs  = ${peer_ip}
        proposals     = aes256-sha256-modp2048
        rekey_time    = 1h
        local {
            auth = psk
            id   = ${self_id}
        }
        remote {
            auth = psk
            id   = ${peer_id}
        }
        children {
            inner-net {
                local_ts     = ${self_inner}
                remote_ts    = ${peer_inner}
                esp_proposals = aes256-sha256
                start_action = trap
                dpd_action   = restart
            }
        }
    }
}

secrets {
    ike-${peer_id} {
        id     = ${peer_id}
        secret = "${PSK_SECRET}"
    }
}
CONF
}

write_swanctl nodes/a/swanctl.conf \
    "branch-a" "branch-b" \
    "$A_PRIMARY" "$B_PRIMARY" \
    "$A_INNER" "$B_INNER"

write_swanctl nodes/b/swanctl.conf \
    "branch-b" "branch-a" \
    "$B_PRIMARY" "$A_PRIMARY" \
    "$B_INNER" "$A_INNER"

echo "[*] Создание node_boot.sh..."
cat > node_boot.sh <<'BOOT'
#!/usr/bin/env bash
# Точка входа для контейнера филиала.
#  1) находит интерфейсы основного и резервного каналов;
#  2) накладывает netem-имитацию реальной задержки;
#  3) поднимает loopback с защищаемым адресом;
#  4) запускает charon и инициирует IPsec-туннель.
set -e

resolve_iface() {
    ip -4 -o addr show \
        | awk -v p="$1" '$4 ~ "^"p {print $2; exit}'
}

IF_PRIMARY="$(resolve_iface '10\.50\.')"
IF_BACKUP="$(resolve_iface  '10\.60\.')"

echo "[boot] основной  : ${IF_PRIMARY:-<none>}"
echo "[boot] резервный : ${IF_BACKUP:-<none>}"

# Основной - быстрый и стабильный
if [ -n "${IF_PRIMARY}" ]; then
    tc qdisc add dev "${IF_PRIMARY}" root netem delay 8ms 1ms
fi
# Резервный - простаивает, на всякий случай добавим небольшую задержку
if [ -n "${IF_BACKUP}" ]; then
    tc qdisc add dev "${IF_BACKUP}" root netem delay 30ms 5ms
fi

case "${NODE_ID:-${NODE:-}}" in
    a) ip addr add 192.168.77.1/32 dev lo ;;
    b) ip addr add 192.168.77.2/32 dev lo ;;
    *) echo "[boot] WARN: NODE_ID не задан, защищённый адрес не повешен" ;;
esac

# strongSwan 5.9 в Alpine лежит в /usr/lib/strongswan/charon
/usr/lib/strongswan/charon &
CHARON_PID=$!

# даём демону время подняться
for _ in $(seq 1 10); do
    [ -S /var/run/charon.vici ] && break
    sleep 0.5
done

swanctl --load-all
swanctl --initiate --child inner-net || true

echo "[boot] IPsec-туннель инициирован, держим контейнер живым"
wait "$CHARON_PID"
BOOT

chmod +x node_boot.sh

cat <<MSG

[+] Готово. Дальше:
    docker compose up --build -d
MSG
